### ISSUE TITLE
decide and document browser support

### ISSUE THREAD

**Issue by flowertwig-org** [StaticWebCMS/core#12]

**Comment by StefanWallin** [comment]
Currently I think this should be the preferred browser support for this:

**Client Web:**
Should not need javascript out of the box.
All browsers out of the box.

**Administration**
- Requires JS
- IE 11 or greater
- Edge/Safari/Firefox/Chrome `CurrentVersion - 1`
- Opera 39
- Android Browser: NO
- Chrome for Android: 52 or greater
- Other: Latest, but not tested, will try to fix bugs.

**Comment by flowertwig-org** [comment]
Sounds good in general :) 
Why specific version for opera? 
And why not greater?

**Comment by StefanWallin** [comment]
Caniuse.com doesn't seem to list any earlier versions for SVG-support :)

**Comment by flowertwig-org** [comment]
But should it not say "Opera 39 or greater" ?  :)

**Comment by StefanWallin** [comment]
Yes Of course :)

**Comment by flowertwig-org** [comment]
ok, then I think we have decided.
Do you document this? :)
